version: '3.0'

services:
  mongodb:
    container_name: 'mongodb'
    image: 'mongo:4'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - ~/apps/mongo:/data/db
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=vti
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/data/db
