version: '3.0'

services:
  mongodb:
    container_name: "mongodb"
    image: "mongo:4"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
  mongodb://root@root/localhost:27017